POST  http://localhost:3000/api/category
Content-Type: application/json

{
  "name": "Dietéticos y Especiales",
  "description": " Productos sin gluten, veganos, proteicos, bajos en azúcar, otros productos especiales."
 
}
