POST http://localhost:3000/api/ingredient
Content-Type: application/json

{
    "name": "Lecitina de Soja",
    "scientificName": "E-322",
    "isBasicFood": false,
    "description": "Emulsionante natural derivado de la soja",
    "allergenType": "SOY",
    "origin": "VEGETAL",
    "additiveType": "EMULSIFIER",
    "servingSize": 1,
    "servingMeasurement": "g",
    "calories": 5,
    "proteins": 0,
    "carbohydrates": 0.2,
    "sugars": 0,
    "fats": 0.5,
    "saturatedFats": 0.1,
    "fiber": 0,
    "risks": [
        {
            "riskType": "ALLERGENIC",
            "level": "MEDIUM"
        }
    ],
    "micronutrients": [
        {
            "micronutrientId": "4ca513d4-446c-4746-9285-ce0e5ec89715",
            "amount": 0.1
        }
    ]
}