@id = 1

PUT http://localhost:3000/api/ingredient/{{id}}
Content-Type: application/json

{
    "id": {{id}},
    "name": "Lecitina de Soja",
    "scientificName": "E-322",
    "isBasicFood": false,
    "description": "Emulsionante natural derivado de la soja. Actualizado",
    "allergenType": "SOY",
    "origin": "VEGETAL",
    "additiveType": "EMULSIFIER",
    "servingSize": 1,
    "servingMeasurement": "g",
    "calories": 5,
    "proteins": 0,
    "carbohydrates": 0.2,
    "sugars": 0,
    "fats": 0.5,
    "saturatedFats": 0.1,
    "fiber": 0,
    "risks": [
        {
            "riskType": "ALLERGENIC",
            "level": "MEDIUM"
        },
        {
            "riskType": "INFLAMMATORY",
            "level": "LOW"
        }
    ],
    "micronutrients": [
        {
            "micronutrientId": "your-micronutrient-id",
            "amount": 0.2
        }
    ]
}